http.host:0.0.0.0
http.port:8081

api.basePath:/api

erp.host:localhost
erp.port:8082
erp.basePath:/erp

sf.username:nisha.tamta199@mindful-koala-t37oq6.com
sf.password:Valium@789
sf.token:ABLexCZ0tqmxFtUGixGIFBCIL
sf.loginUrl=https://login.salesforce.com/services/Soap/u/60.0